/**
 *
 * $Id$
 */
package org.talend.core.model.properties.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.talend.core.model.properties.RoutinesJarType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoutinesJarTypeValidator {
    boolean validate();

    boolean validateMvnUrl(String value);
    boolean validateImports(EList value);
}
