/**
 *
 * $Id$
 */
package org.talend.core.model.properties.validation;

import org.talend.core.model.properties.RoutinesJarType;

/**
 * A sample validator interface for {@link org.talend.core.model.properties.RoutinesJarItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoutinesJarItemValidator {
    boolean validate();

    boolean validateRoutinesJarType(RoutinesJarType value);
}
